let score=prompt("Enter score of student: ");
if(score>=80 && score<=100){
    alert("The grade of student is A")
}
else if(score>=70 && score<=89){
    alert("The grade of student is B")
}
else if(score>=60 && score<=69){
    alert("The grade of student is C")
}
else if(score>=50 && score<=59){
    alert("The grade of student is D")
}
else if(score>=0 && score<=49){
    alert("The grade of student is F")
}